export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS'

}

export const categoryConstants = {
    GET_CATEGORY_REQUEST : 'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCESS : 'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAILURE : 'GET_CATEGORY_FAILURE',

    ADD_CATEGORY_REQUEST : 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS : 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE : 'ADD_CATEGORY_FAILURE'
}

export const productConstants = {
    GET_PRODUCT_BY_SLUG_REQUEST : 'GET_PRODUCT_BY_SLUG_REQUEST',
    GET_PRODUCT_BY_SLUG_SUCCESS : 'GET_PRODUCT_BY_SLUG_SUCCESS',
    GET_PRODUCT_BY_SLUG_FAILURE : 'GET_PRODUCT_BY_SLUG_FAILURE',

    GET_PRODUCT_BY_PAGE_REQUEST : 'GET_PRODUCT_BY_PAGE_REQUEST',
    GET_PRODUCT_BY_PAGE_SUCCESS : 'GET_PRODUCT_BY_PAGE_SUCCESS',
    GET_PRODUCT_BY_PAGE_FAILURE : 'GET_PRODUCT_BY_PAGE_FAILURE',


    GET_PRODUCT_REQUEST : 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS : 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE : 'GET_PRODUCT_FAILURE',

    ADD_PRODUCT_REQUEST : 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE : 'ADD_PRODUCT_FAILURE',

    GET_PRODUCT_DETAILS_BY_ID_REQUEST : 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS : 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE : 'GET_PRODUCT_DETAILS_BY_ID_FAILURE',


    CHANGE_CATEGORY_GET_PRODUCT : 'CHANGE_CATEGORY_GET_PRODUCT'
}

export const initialDataConstants = {
    GET_INITIALDATA_REQUEST : 'GET_INITIALDATA_REQUEST',
    GET_INITIALDATA_SUCCESS : 'GET_INITIALDATA_SUCCESS',
    GET_INITIALDATA_FAILURE : 'GET_INITIALDATA_FAILURE',

}

export const cartConstants = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
    RESET_CART: "RESET_CART",
  
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
  };

  export const userConstants = {
    GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
    GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
    GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",
    ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
    ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
    ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",
    ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
    ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
    ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
    GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
    GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",
  
    GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
    GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
    GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",
  };